### ISSUE TITLE
Test 3

### ISSUE THREAD

**Issue by aoderinde** [affilinet/productdata-php-sdk#4]
Test Email Notification

**Comment by sgotre** [comment]
kam an, danke!

**Comment by aoderinde** [comment]
Perfekt ☺

Von: sgotre [mailto:notifications@github.com]
Gesendet: Mittwoch, 16. November 2016 14:19
An: affilinet/productdata-php-sdk <productdata-php-sdk@noreply.github.com>
Cc: Oderinde, Alice - affilinet GmbH <aoderinde@affili.net>; Author <author@noreply.github.com>
Betreff: Re: [affilinet/productdata-php-sdk] Test 3 (#4)


kam an, danke!
