### ISSUE TITLE
Original Image is not in include

### ISSUE THREAD

**Issue by benjaminfunk** [affilinet/productdata-php-sdk#5]
The default action does not include the original image.

`public function addAllProductImages()
    {
        $this
            ->addProductImageWithSize30px()
            ->addProductImageWithSize60px()
            ->addProductImageWithSize90px()
            ->addProductImageWithSize120px()
            ->addProductImageWithSize180px();

        return $this;
    }`

The method addProductImage is never called

**Comment by sgotre** [comment]
HI Benjamin, 
thanks a lot for mentioning this one. I will create an update and publish it this afternoon.

**Comment by sgotre** [comment]
The image was is now included in commit https://github.com/affilinet/productdata-php-sdk/commit/eb3f2a953dc4fb0e5d29cbdb65524d3c19aec934  We will publish it with version 1.0.1.
