### ISSUE TITLE
403 Status on Live server

### ISSUE THREAD

**Issue by benjaminfunk** [affilinet/productdata-php-sdk#6]
`$objGuzzleClient = new \GuzzleHttp\Client(
	[
		'verify' => isEnvironment('development') ? false : true
	]);

	$objHttpClient = new \Affilinet\ProductData\HttpClient\GuzzleClient($objGuzzleClient);

	$arrConfig =
	[
		'publisher_id' => xxxxx,
		'product_webservice_password' => 'xxxxx',
		'http_client' => $objHttpClient
	];

	$objClient = new \Affilinet\ProductData\AffilinetClient($arrConfig);

	$objProductSearch = (new \Affilinet\ProductData\Requests\ProductsRequest($objClient));

	$objProductSearch->pageSize(500);
	$objProductSearch->addFilterQuery('EAN', '04260415994004');

	$objProductsResponse = $objProductSearch->send();`

This code works well on my local environment. But if i use it on my live server i always get a 403.

`{"ErrorMessages":[{"Key":"20300007","Value":"PublisherId is not valid. The PublisherId has to be greater than 0."}]}`

cURL - installed 7.38.0
openSSL - installed OpenSSL/1.0.1t
zlib - installed

Any ideas why it isnt working and how i can debug this?

Hey,

for my tests its hard-coded. But a string will not solve the problem.

I cant comment. WTF!?

**Comment by sgotre** [comment]
Hi Benjamin, 
Is the publisher ID hard-coded? Could you please try if it works if you add it as a string?

**Comment by benjaminfunk** [comment]
Hey,

for my tests its hard-coded. But a string will not solve the problem.

**Comment by benjaminfunk** [comment]
I tried a simple Guzzle Request

`$client = new \GuzzleHttp\Client(
	[
		'verify' => isEnvironment('development') ? false : true
	]);

	$res = $client->request('GET', 'https://product-api.affili.net/V3/productservice.svc/JSON/SearchProducts?PublisherId=xxx&Password=xxxx&Query=ipod');

	echo $res->getStatusCode();
	echo $res->getHeaderLine('content-type');
	echo $res->getBody();`

This will work! But its nearly the same, except the Affilinet Lib.

**Comment by sgotre** [comment]
Did you maybe set an Environment Variable named 'AFFILINET_PUBLISHER_ID'

This could overwrite your config, see code here: https://github.com/affilinet/productdata-php-sdk/blob/master/src/Affilinet/ProductData/AffilinetClient.php#L65

**Comment by benjaminfunk** [comment]
In my real application i have set this environment var. But with the right value.

In my current sandbox the var is not set. So this cant be the problem

**Comment by sgotre** [comment]
Ok i just did a re-check: The environment var gets overwritten by the hardcoded publisher id. The same applies to you publisher password. So on your live-server the env var will not be used.

**Comment by sgotre** [comment]
if you want you can call me 0049 176 24430060. so we could discuss this faster :)

**Comment by benjaminfunk** [comment]
Are you german? Will be a bit easier for me ;)

**Comment by sgotre** [comment]
yes :)

**Comment by benjaminfunk** [comment]
Bin um einiges weiter gekommen. Folgendes ist mir aufgefallen. In meinem simple Guzzle Request nutze ich die Methode request

`$client->request();`

Der GuzzleClient nutzt allerdings eine send Methode (https://github.com/affilinet/productdata-php-sdk/blob/master/src/Affilinet/ProductData/HttpClient/GuzzleClient.php#L49)

Wenn ich die Zeile 49 nun durch folgendes ersetze

`$psr7Response = $this->guzzle->request('GET', $request->getUri()->__toString());`

funktioniert es! :)

Ist meiner Meinung nach noch nicht die sauberste Lösung, aber du solltest damit denke ich schnell zu einer Lösung kommen.

**Comment by sgotre** [comment]
Interessant, dass es hier zu unterschiedlichem Verhalten kommt. Muss mal recherchieren ob es hier irgendwelche Änderungen in Guzzle gab

**Comment by benjaminfunk** [comment]
https://github.com/guzzle/guzzle/blob/master/docs/request-options.rst#headers

Ich kann mir vorstellen das irgendwelche Standard Header nicht gesetzt werden und deswegen vielleicht meine Security Erweiterung (Suhosin) alles blockt.

**Comment by benjaminfunk** [comment]
Gibt es schon irgendwelche Neuigkeiten/Lösungen oder muss ich vorerst auf ein Workaround zurückgreifen?

**Comment by sgotre** [comment]
Hallo Benjamin, 
ich habe versucht den Fall nachzustellen, mir ist es allerdings nicht gelungen. 
Die Ursache liegt also nicht im Code sondern in der Umgebung. 

Wir hatten ja im Juni telefoniert, und ich bin mir sicher, dass es die genannte PHP-Sicherheitserweiterung ist die hier die Probleme macht. 
Diese würde ich deaktivieren, sofern sie nicht unbedingt benötigt wird. 

Sorry, dass ich hier nicht weiter helfen kann.

**Comment by benjaminfunk** [comment]
Hey,

kein Problem. Ich hab mich nochmal ran gesetzt und habe den Fehler gefunden :)

https://github.com/affilinet/productdata-php-sdk/blob/master/src/Affilinet/ProductData/Requests/AbstractRequest.php#L56

Das Problem ist das http_build_query auf manchen Servern automatisch ein "&" nach "&amp;" ersetzt. Wenn man es in HTML verwendet ist das kein Problem. Als Request URI macht es allerdings Probleme.

Dieses Verhalten ist bekannt: http://php.net/manual/de/function.http-build-query.php#102324

Am einfachten wäre vermutlich die Verwendung von "http_build_query($query, '', '&');". Könntest du das mal durch deine Tests überprüfen lassen? Man könnte diese Option ja auch optional per Variable umstellen.

**Comment by sgotre** [comment]
Ja großartig, man lernt aber auch nie aus! Habe eben die Version 1.0.1 veröffentlicht. Darin ist es behoben.
