### ISSUE TITLE
Planned Features

### ISSUE THREAD

**Issue by develth** [affilinet/productdata-php-sdk#7]
Hey there, 

i just wanted to know if its planned to integrate the PublisherStatistics or Account endpoint?

Thanks, 
Thomas

**Comment by avaffilinet** [comment]
Dear Thomas,

not at the moment. The PHP SDK is only available for our Product Data Webservice endpoint.

**Comment by develth** [comment]
Hey @avaffilinet 

ok - because i was wondering about the Shop-Endpoint integration. 
Then i will fork & extend, otherwise it would be useless :(

Thanks!
